### ISSUE TITLE
Some task-resulting calls  for local backaned always return Error 500

### ISSUE THREAD

**Issue by AlexMKX** [proxmoxer/proxmoxer#146]
```
from proxmoxer import ProxmoxAPI

c = ProxmoxAPI(backend='local')
c.set('nodes/pve2/network')
```
always return Error 500 with UPID.
Expected result - successfull return and UPID

**Comment by keviiin38** [comment]
+1 

Same error for me when calling `proxmox.nodes("pve").network.put()`

```python
>>> proxmox.nodes("pve").network.put()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/proxmoxer/core.py", line 175, in put
    return self(args)._request("PUT", data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/proxmoxer/core.py", line 158, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 500 Internal Server Error: "UPID:pve:[...]:srvreload:networking:root@pam:"
```

Version:
- Proxmox VE:  **8.0.4**
- Proxmoxer: **2.0.1**
- Backend: **local**

**Comment by jhollowe** [comment]
if you run the pvesh command on the PVE node, what exit code does it return?

e.g. `pvesh set nodes/pve/network ; echo $?`
