### ISSUE TITLE
I can't install proxmoxer

### ISSUE THREAD

**Issue by gregoryca** [proxmoxer/proxmoxer#166]
Keep getting the same error. Other hosts produce the same error sadly :(
![cannot install proxmox](https://github.com/proxmoxer/proxmoxer/assets/10562868/9602108b-e071-43ea-ac34-62cdefb3ed2f)

**Comment by morph027** [comment]
Looks like your `pip` command is python2 oder older python3 which does not understand the f-Syntax.

Can you post the output of `pip -V`?

**Comment by gregoryca** [comment]
Thank you very much for your quick anwer. The command outputs the following:
`pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)`
So i think it indeed defaults to the older pip installed on the OS. This is on the latest version of Proxmox VE.

Should i add the newer python install to my path ?

**Comment by morph027** [comment]
You could try `pip3 install proxmoxer`

**Comment by gregoryca** [comment]
`root@pve:~# pip3 install proxmoxer
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip._internal import main
  File "/usr/lib/python3/dist-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 23, in <module>
    from pip._internal.index import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 14, in <module>
    from pip._vendor import html5lib, requests, six
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)`

:( I tried installing pip3 put cannot seem to find a way to install it on my server :(

**Comment by morph027** [comment]
Looks like your python installation is messed up somehow. Which PVE version are you running?

**Comment by gregoryca** [comment]
I thought so but I was scared to make that conclusion. I'm running 8.2 pve installed from the iso. Other than this I have no issues.

**Comment by jhollowe** [comment]
As mentioned above, it looks like there is just something wrong with your python/pip installation. I'm going to close this, but feel free to reopen if this keeps happening after a fix/reinstall of python
