### ISSUE TITLE
Wrong pve node name in config

### ISSUE THREAD

**Issue by SAOPP** [proxmoxer/proxmoxer#41]
This issue is based at my own "bug" report 'bout this intergration, here is the original topic: https://github.com/home-assistant/core/issues/42637#issue-733214557

For reproduce:
For-example your node called is **proxmox**, just add integration config like this:

```
proxmoxve:
  - host: 192.168.0.9
    verify_ssl: false
    username: homeassistant
    password: password
    realm: pve
    nodes:
      - node: Proxmox <-- for example first letter is uppercase
        vms:
...
```

Next, u will see this answer in HA log 'bout the issue with this integration:

```
proxmoxve: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/proxmoxve/binary_sensor.py", line 83, in update
    item = self.poll_item()
  File "/usr/src/homeassistant/homeassistant/components/proxmoxve/binary_sensor.py", line 94, in poll_item
    self._proxmox_client.get_api_client()
  File "/usr/local/lib/python3.8/site-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.8/site-packages/proxmoxer/core.py", line 90, in _request
    raise ResourceException("{0} {1}: {2} - {3}".format(
proxmoxer.core.ResourceException: 596 Errors during TLS negotiation, request sending and header processing: tls_process_server_certificate: certificate verify failed - b''
```

Based on the response in Home Assistant logs completely is not clear what this integration needs. I think this needs to be fixed, and a check should be added with the answer that such a node was NOT FOUND. After such an answer, I hope users will not have any questions, which was not true.

But in fact, guys, I thought, maybe just correct the description of the integration, where to describe in more detail the importance of the coincidence of the node name from the hypervisor with the config in the Home Assistant?

Ok, thanks in advance! Best regards.

**Comment by jhollowe** [comment]
Basically, non-existent node names and incorrectly capitalized node names are treated differently and have errors that are not handled. We need to add error handling for these and possibly communicate with Proxmox on why these errors are different.

**Comment by SAOPP** [comment]
And by the way, yes, you're right, but I came across only 1 error, which I shared above, but one user in my topic, if I'm not mistaken, posted different errors. Maybe I'm wrong, I should check it out.
